WIP: connecting to mysql
oreotabetai/user-auth-jwt-python-api pull request #28
Opened 2020-11-05 09:28 UTC by yamakenji24

2020-11-07 17:52 UTC, yamakenji24 commented
## What i did in this PR
### Mysql Connection
- connect to mysql in db.py
- connections requires some config data, which can be used from env or by default.
-

2020-11-10 10:26 UTC, wakatakeru requested changes
request changes

2020-11-10 10:26 UTC, wakatakeru commented on .gitignore
> +*/**/__pycache__
recommend adding new line

2020-11-10 10:26 UTC, wakatakeru commented on server.py
> +@app.get("/users/me")
change `/users/me` to `/my`

2020-11-10 10:26 UTC, wakatakeru commented on src/db.py
> +Base.query = session.query_property()
recommend adding new line

2020-11-10 10:41 UTC, wakatakeru approved these changes
LGTM!

2020-11-10 10:41 UTC, merged